trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Use Python 3.12'

- script: |
    pip install -r environment.yml
    python -m pytest tests/
  displayName: 'Install dependencies and run tests'

- script: |
    docker build -t $(Build.Repository.Name):$(Build.BuildId) .
  displayName: 'Build Docker Image'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'recommend.azurecr.io/$(Build.Repository.Name)'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'RecommendACRConnection'
    tags: |
      $(Build.BuildId)
  displayName: 'Push image to ACR'
